### ISSUE TITLE
Implementing shape

### ISSUE THREAD

**Issue by amitsingh19975** [BoostGSoC19/tensor#3]
[1](url) ) shape for storing extents
2 ) shape concat for concat two shape
3 ) make dynamic shape which will create shape based on size

1. `shape` is use to hold the extents of tensor
     for example 
         `shape<1,2,3,4,5,6>` where 1,2,3,4,5,6 are extents  of tensor of rank 6
     **Members**
         - `type` contains the type of `shape` 
         - `rank` contains the rank of type `ptrdiff_t`

2. `concat_shape` is use to concat two shape into one, similar to zip
      for ex:- 
       `using s1 = shape<1,2,3,4>`
       `using s2 = shape<5,6,7,8>`
       `using s3 = concat_shape<s1,s2>` ==> `shape<1,2,3,4,5,6,7,8>` of rank 8

     **Members**
         - `type` contains the type of `shape` 

3. `make_dynamic_shape` is for making dynamic extents
      example:-
        `make_dynamic_shape<3>` ==> `shape<dynamic_extent, dynamic_extent, dynamic_extent >`
     **Members**
       - `type` contains the type of `shape` 

**path: https://github.com/BoostGSoC19/tensor/blob/framework/include/boost/numeric/ublas/tensor/shape_helper.hpp**

**Comment by bassoy** [comment]
What is a sequence?

**Comment by amitsingh19975** [comment]
> What is a sequence?

basically its a way to store and dynamic extent 
for ex: 
1 ) auto make_seq<3,1,5,3> ==> seq<1,5,3> 
     where 3 is size of seq
2 ) auto make_seq<3> ==> seq<dynamic_extent, dynamic_extent, dynamic_extent>
     normally in mdspan you have to provide extents its just wrapper for extent

This thing can found in my implementation of mdspan

**Comment by bassoy** [comment]
Thanks Amit. Sequence is a very generic name and cold anything. I suggest to take 'extents' or 'shape'.

**Comment by amitsingh19975** [comment]
Im very bad with names

**Comment by bassoy** [comment]
That's okay. We just have to be sure that other people understand what we do; by not reading our comments but our code ;-)

**Comment by bassoy** [comment]
How about: "implementing a generic shape type"
In general I like your idea of implementing a generic type for the shape of a tensor.

**Comment by amitsingh19975** [comment]
its a utility function there's more to implement

**Comment by amitsingh19975** [comment]
when I implement whole mdspan it will act as shape and I have implemented it in https://github.com/amitsingh19975/tensor_extent_testing which you can see

**Comment by bassoy** [comment]
This ` template< ptrdiff_t ...Is > struct seq{/*...*/};` is a class template which helps to create static extents `struct extents : private detail::extents_impl< 0, detail::make_seq_t<dims, StaticExtents...>>`
right?

**Comment by amitsingh19975** [comment]
yes
