### ISSUE TITLE
Reviewing Implementation of extents_helper

### ISSUE THREAD

**Issue by bassoy** [BoostGSoC19/tensor#32]
Regarding [extents_helper.cpp](https://github.com/BoostGSoC19/tensor/blob/framework/include/boost/numeric/ublas/tensor/extents_helper.hpp):

Why does a `basic_shape_t` needs to be a template parameter of `basic_extents_impl` 
```cpp
template <ptrdiff_t R, class S /*=base_shape_t*/> 
struct basic_extents_impl;
```
which is then specialized for shapes types with zero modes and with rank greater zero.
The helper should be based on the static extents only.

**Comment by amitsingh19975** [comment]
this creates static rank with dynamic extents. 
similar to c++ integer seq basic_shape_t is a way to create and store extents at compile time
1. `make_basic_shape_t <4,1,2,3,4>` =>` basic_shape<1,2,3,4>`
2. `make_basic_shape_t <4>` => `basic_shape<-1,-1,-1,-1>`
where -1 is for dynamic_extents.
it is similar to `std::make_index_sequence` and `std::index_sequence`
