### ISSUE TITLE
 CI servers run out of virtual memory

### ISSUE THREAD

**Issue by bassoy** [BoostGSoC19/tensor#46]
With greater test coverage @coder3101 hinted that **unit tests of tensor are very big once macros** are expanded and also this **is more prominent in case of tests involving expression**

> Initially my change used to cause Appveyor to run out of heap memory during compilation. Later today Travis ran out of memory. It even causes my computer to hang (8GB RAM) during compilation of test_tensor_expression.cpp

**Comment by bassoy** [comment]
Solution for this is proposed by @coder3101:

> In order to mitigate this issue we have to divide the big tests into smaller individual files.

**Comment by coder3101** [comment]
As of now, https://github.com/BoostGSoC19/tensor/blob/expr_template/test/tensor/test_expression_comparision1.cpp file takes maximum compile memory on gcc. Around 3.5 GB virtual memory for parser and 2GB of virtual memory by assembler afterwards. Travis offers 7.5GB memory for Linux environment. The current workaround is to disable parallel compilation of tests. This does impacts CI compile time to about 25% more.

**Comment by coder3101** [comment]
I have further divided the above-mentioned file into 2 separate tests. The builds are now passing, Maximum memory used in GCC during a non-parallel compilation period is 1.7GB. 

> **Here is a tip for the other test authors. Heavy use of `==` and `!=` can cause the compiler to use more memory as these operators use more `boost::yap::transform` than other operators.**

**Comment by coder3101** [comment]
In the last referenced commit the extra transforms for `==` and `!=` are removed and now the max memory usage for compilation is around 1.4 GB, As this point, we can re-enable parallel compilation but I am just leaving it. 

This issue can be marked as resolved after the following steps are taken:
- `test_tensor.cpp` should be divided into smaller test files.
- `test_functions.cpp` should be divided into smaller test files.

Collaborators working with these files are requested to bring in the changes.

**Comment by coder3101** [comment]
Since we are making our move to bring tensor-level optimizations to YAP Expressions this issue will be fixed. Initially, we had element-level optimization and hence compiler used to take a lot of time and memory to optimize for each element. (as optimization is done at compile time). I will mark it resolved as we reach some conclusion on how to bring tensor-level optimization.

**Comment by coder3101** [comment]
Closing this Issue for now as we are now doing Runtime optimization of expressions instead of compile time that uses more memory.
